import Link from 'next/link';
const links:any={featured:'https://buy.stripe.com/eVq9AV1Pp2m841mdnD2wU04',calculator:'https://buy.stripe.com/bJe5kF9hR6CogO8erH2wU05',category:'https://buy.stripe.com/8x29AV51BbWIbtO6Zf2wU06',market:'https://buy.stripe.com/00wcN79hR0e07dy3N32wU07',spotlight:'https://buy.stripe.com/3cIfZj51Bf8U69ugzP2wU08'};
const C:any={
en:{ey:'SEE YOUR BRAND IN THE HUB',title:'Know exactly what you are buying.',lead:'Preview each placement before checkout. Every paid placement is clearly labeled Sponsored.',brand:'YOUR BRAND HERE',sponsored:'Sponsored',preview:'Placement preview',recommended:'RECOMMENDED',buy:'Buy with Stripe →',month:'/ month',once:'one-time · 30 days',custom:'Need a custom campaign or multiple markets?',talk:'Talk to us →'},
pt:{ey:'VEJA SUA MARCA NO HUB',title:'Saiba exatamente o que está comprando.',lead:'Visualize cada posição antes do pagamento. Toda publicidade é claramente identificada como Patrocinado.',brand:'SUA MARCA AQUI',sponsored:'Patrocinado',preview:'Prévia da posição',recommended:'RECOMENDADO',buy:'Contratar com Stripe →',month:'/ mês',once:'pagamento único · 30 dias',custom:'Precisa de uma campanha personalizada ou vários mercados?',talk:'Falar conosco →'},
es:{ey:'VE TU MARCA EN EL HUB',title:'Mira exactamente lo que estás comprando.',lead:'Previsualiza cada ubicación antes de pagar. Toda publicidad se identifica claramente como Patrocinado.',brand:'TU MARCA AQUÍ',sponsored:'Patrocinado',preview:'Vista previa',recommended:'RECOMENDADO',buy:'Contratar con Stripe →',month:'/ mes',once:'pago único · 30 días',custom:'¿Necesitas una campaña personalizada o varios mercados?',talk:'Hablar con nosotros →'},
de:{ey:'IHRE MARKE IM HUB',title:'Sehen Sie genau, was Sie kaufen.',lead:'Vorschau jeder Platzierung vor dem Checkout. Bezahlte Werbung wird klar als Gesponsert gekennzeichnet.',brand:'IHRE MARKE HIER',sponsored:'Gesponsert',preview:'Platzierungsvorschau',recommended:'EMPFOHLEN',buy:'Mit Stripe buchen →',month:'/ Monat',once:'einmalig · 30 Tage',custom:'Individuelle Kampagne oder mehrere Märkte?',talk:'Kontakt →'},
ja:{ey:'HUBでのブランド表示例',title:'購入前に掲載イメージを確認できます。',lead:'各掲載枠を決済前に確認できます。広告はすべて「スポンサー」と明確に表示されます。',brand:'あなたのブランド',sponsored:'スポンサー',preview:'掲載プレビュー',recommended:'おすすめ',buy:'Stripeで申し込む →',month:'/ 月',once:'1回払い · 30日',custom:'カスタムキャンペーンや複数市場をご希望ですか？',talk:'お問い合わせ →'}};
const P:any={
en:[['featured','Featured Partner',49,'A clean featured card on relevant Hub pages.'],['calculator','Calculator Sponsor',99,'Your brand beside a high-intent calculator result.'],['category','Category Sponsor',249,'Premium visibility across a calculator or guide category.'],['market','Market Sponsor',399,'Premium sponsorship for one country hub.'],['spotlight','Launch Spotlight',149,'A stronger 30-day block for a launch or campaign.']],
pt:[['featured','Parceiro em Destaque',49,'Card de destaque integrado às páginas relevantes do Hub.'],['calculator','Patrocínio de Calculadora',99,'Sua marca ao lado do resultado de uma calculadora de alta intenção.'],['category','Patrocínio de Categoria',249,'Visibilidade premium em uma categoria de calculadoras ou guias.'],['market','Patrocínio de Mercado',399,'Patrocínio premium de um hub de país.'],['spotlight','Destaque de Lançamento',149,'Bloco promocional de maior destaque por 30 dias.']],
es:[['featured','Socio Destacado',49,'Tarjeta destacada integrada en páginas relevantes.'],['calculator','Patrocinio de Calculadora',99,'Tu marca junto al resultado de una calculadora.'],['category','Patrocinio de Categoría',249,'Visibilidad premium en una categoría.'],['market','Patrocinio de Mercado',399,'Patrocinio premium de un hub de país.'],['spotlight','Destaque de Lanzamiento',149,'Bloque promocional destacado durante 30 días.']],
de:[['featured','Featured Partner',49,'Hervorgehobene Markenkarte auf relevanten Hub-Seiten.'],['calculator','Rechner-Sponsor',99,'Ihre Marke direkt neben einem Rechnerergebnis.'],['category','Kategorie-Sponsor',249,'Premium-Sichtbarkeit in einer Kategorie.'],['market','Markt-Sponsor',399,'Premium-Sponsoring für einen Länder-Hub.'],['spotlight','Launch Spotlight',149,'Prominenter Kampagnenblock für 30 Tage.']],
ja:[['featured','注目パートナー',49,'関連ページにブランドカードを掲載。'],['calculator','計算ツールスポンサー',99,'計算結果の近くにブランドを掲載。'],['category','カテゴリースポンサー',249,'カテゴリー全体でプレミアム表示。'],['market','市場スポンサー',399,'国別Hubのプレミアムスポンサー。'],['spotlight','ローンチスポットライト',149,'30日間の高視認性プロモーション。']]};
function Mock({kind,t}:{kind:string,t:any}){return <div className={'adMock adMock-'+kind}><div className="mockBrowser"><i/><i/><i/><span>Business Calculator Hub</span></div><div className="mockPage"><div className="mockNav">BUSINESS CALCULATOR HUB <b>Calculators&nbsp;&nbsp; Guides</b></div>{kind==='market'?<div className="mockHero"><small>{t.sponsored}</small><strong>{t.brand}</strong><span>Premium market partner</span><button>Learn more →</button></div>:<div className="mockCalc"><div><span>Profit Margin Calculator</span><strong>35.00%</strong><em>Revenue &nbsp; Costs &nbsp; Margin</em></div><aside><small>{t.sponsored}</small><b>{t.brand}</b><p>{kind==='spotlight'?'Featured campaign for business decision makers.':'Tools for smarter business decisions.'}</p><button>Learn more →</button></aside></div>}{kind==='category'&&<div className="mockStrip"><small>{t.sponsored}</small><b>{t.brand}</b><span>Category partner</span></div>}</div></div>}
export default function AdvertisingPlans({lang='en',contact='#proposal'}:{lang?:'en'|'pt'|'es'|'de'|'ja';contact?:string}){const t=C[lang];const features:any={en:['Brand placement','Contextual message + CTA','Tracked destination link'],pt:['Posição da marca','Mensagem contextual + CTA','Link de destino rastreado'],es:['Ubicación de marca','Mensaje contextual + CTA','Enlace de destino rastreado'],de:['Markenplatzierung','Kontextbotschaft + CTA','Tracking-Link'],ja:['ブランド掲載','文脈に合うメッセージ + CTA','計測可能リンク']}[lang];return <section className="adPlansSection" id="plans"><div className="sectionHeading"><div><p className="eyebrow">{t.ey}</p><h2>{t.title}</h2></div><p>{t.lead}</p></div><div className="adPlanGrid">{P[lang].map((p:any)=><article className={'adPlan '+(p[0]==='calculator'?'adPlanRecommended':'')} key={p[0]}>{p[0]==='calculator'&&<span className="recommendBadge">{t.recommended}</span>}<Mock kind={p[0]} t={t}/><div className="adPlanBody"><span className="tag">{t.preview}</span><h3>{p[1]}</h3><div className="adPrice"><strong>{'$'}{p[2]}</strong><span>{p[0]==='spotlight'?t.once:t.month}</span></div><p>{p[3]}</p><ul>{features.map((x:string)=><li key={x}>✓ {x}</li>)}</ul><a className="primary adBuy" href={links[p[0]]} target="_blank" rel="noopener noreferrer">{t.buy}</a></div></article>)}</div><div className="adCustom"><strong>{t.custom}</strong><a href={contact}>{t.talk}</a></div></section>}