import Link from 'next/link';

type Locale='pt-br'|'es-mx'|'es-cl'|'de-de'|'en-in'|'ja-jp'|'en-gb';
const base='https://business-calculator-hub.vercel.app';
const formulas:Record<string,string>={
'freelance-rate-calculator':'Hourly rate = (target annual income + annual expenses) ÷ (1 − tax rate) ÷ billable hours',
'roi-calculator':'ROI (%) = (return − investment) ÷ investment × 100',
'salary-to-hourly-calculator':'Hourly rate = annual salary ÷ (hours per week × working weeks per year)',
'markup-calculator':'Selling price = cost × (1 + markup %)',
'break-even-calculator':'Break-even units = fixed costs ÷ (selling price − variable cost per unit)',
'payback-period-calculator':'Payback period = initial investment ÷ annual cash return',
'cac-ltv-calculator':'CAC = marketing spend ÷ new customers; LTV ≈ monthly revenue per customer ÷ monthly churn rate',
'runway-calculator':'Runway (months) = available cash ÷ monthly burn',
'selling-price-calculator':'Selling price = cost ÷ (1 − target margin)',
'discount-margin-calculator':'Discounted price = original price × (1 − discount); margin = (price − cost) ÷ price',
'fixed-project-price-calculator':'Project price = estimated hours × target hourly value × (1 + safety margin)',
'project-hourly-rate-calculator':'Project hourly rate = (income target + expenses) ÷ available working hours',
'freelance-vs-salary-calculator':'Compare annual employment compensation with freelance revenue after expenses and estimated taxes'};
const text:Record<Locale,string[]>={
'pt-br':['O que esta calculadora faz?','Fórmula e metodologia','Exemplo de uso','Quando usar','Limitações','Perguntas frequentes','Calculadoras relacionadas','Use esta ferramenta para transformar dados financeiros ou profissionais em uma estimativa objetiva para apoiar sua decisão.','Preencha os campos com seus próprios valores. O resultado é recalculado imediatamente para comparar cenários.','Use antes de definir preços, avaliar investimentos, planejar caixa ou comparar alternativas de trabalho e negócio.','O resultado é uma estimativa educacional. Confirme obrigações legais e tributárias em fontes oficiais.','Posso usar o resultado para tomar uma decisão financeira?','Use-o como referência e análise de cenário, não como aconselhamento financeiro, jurídico ou tributário individual.','A calculadora é gratuita?','Sim. As calculadoras são gratuitas e não exigem login.'],
'es-mx':['¿Qué hace esta calculadora?','Fórmula y metodología','Ejemplo de uso','Cuándo usarla','Limitaciones','Preguntas frecuentes','Calculadoras relacionadas','Convierte datos financieros o profesionales en una estimación objetiva para apoyar una decisión.','Ingresa tus propios valores. El resultado se actualiza de inmediato para comparar escenarios.','Úsala antes de fijar precios, evaluar inversiones, planificar caja o comparar opciones de trabajo y negocio.','El resultado es una estimación educativa. Verifica obligaciones legales y fiscales con fuentes oficiales.','¿Puedo usar el resultado para tomar una decisión financiera?','Úsalo como referencia y análisis de escenarios, no como asesoría financiera, legal o fiscal personalizada.','¿La calculadora es gratuita?','Sí. Es gratuita y no requiere iniciar sesión.'],
'es-cl':['¿Qué hace esta calculadora?','Fórmula y metodología','Ejemplo de uso','Cuándo usarla','Limitaciones','Preguntas frecuentes','Calculadoras relacionadas','Convierte datos financieros o profesionales en una estimación objetiva para apoyar una decisión.','Ingresa tus propios valores. El resultado se actualiza inmediatamente para comparar escenarios.','Úsala antes de fijar precios, evaluar inversiones, planificar caja o comparar opciones de trabajo y negocio.','El resultado es una estimación educativa. Verifica obligaciones legales y tributarias con fuentes oficiales.','¿Puedo usar el resultado para tomar una decisión financiera?','Úsalo como referencia y análisis de escenarios, no como asesoría financiera, legal o tributaria personalizada.','¿La calculadora es gratuita?','Sí. Es gratuita y no requiere iniciar sesión.'],
'de-de':['Was berechnet dieses Tool?','Formel und Methodik','Anwendungsbeispiel','Wann verwenden?','Grenzen der Berechnung','Häufige Fragen','Verwandte Rechner','Dieses Tool wandelt finanzielle oder berufliche Eingaben in eine nachvollziehbare Schätzung zur Entscheidungsunterstützung um.','Tragen Sie Ihre Werte ein. Das Ergebnis wird sofort neu berechnet, sodass Sie Szenarien vergleichen können.','Nutzen Sie den Rechner vor Preisentscheidungen, Investitionen, Liquiditätsplanung oder dem Vergleich geschäftlicher Alternativen.','Das Ergebnis ist eine Orientierung. Prüfen Sie rechtliche und steuerliche Pflichten anhand offizieller Quellen.','Kann ich das Ergebnis für eine finanzielle Entscheidung verwenden?','Nutzen Sie es als Szenarioanalyse, nicht als individuelle Finanz-, Rechts- oder Steuerberatung.','Ist der Rechner kostenlos?','Ja. Er ist kostenlos und ohne Anmeldung nutzbar.'],
'en-in':['What does this calculator do?','Formula and methodology','Example use','When to use it','Limitations','Frequently asked questions','Related calculators','Turn business or work inputs into a transparent estimate that can support a decision.','Enter your own values. The result updates immediately so you can compare scenarios.','Use it before setting prices, evaluating investments, planning cash, or comparing work and business options.','The result is an educational estimate. Verify legal or tax obligations with official sources.','Can I use the result to make a financial decision?','Use it as a reference and scenario analysis, not personalised financial, legal or tax advice.','Is the calculator free?','Yes. It is free and does not require a login.'],
'ja-jp':['この計算ツールで何が分かりますか？','計算式と方法','使用例','使うタイミング','注意点','よくある質問','関連する計算ツール','ビジネスや仕事の入力値を、意思決定に役立つ分かりやすい概算へ変換します。','ご自身の数値を入力すると結果がすぐ更新され、複数のシナリオを比較できます。','価格設定、投資判断、資金計画、働き方や事業案の比較を行う前に利用できます。','結果は教育目的の概算です。法務・税務上の義務は公式情報で確認してください。','結果をそのまま財務判断に使えますか？','シナリオ分析の参考として利用し、個別の金融・法務・税務助言の代替にはしないでください。','無料で使えますか？','はい。無料で、ログインも不要です。'],
'en-gb':['What does this calculator do?','Formula and methodology','Example use','When to use it','Limitations','Frequently asked questions','Related calculators','Turn business or work inputs into a transparent estimate that can support a decision.','Enter your own values. The result updates immediately so you can compare scenarios.','Use it before setting prices, evaluating investments, planning cash, or comparing work and business options.','The result is an educational estimate. Verify legal or tax obligations with official sources.','Can I use the result to make a financial decision?','Use it as a reference and scenario analysis, not personalised financial, legal or tax advice.','Is the calculator free?','Yes. It is free and does not require a login.']};
const related=['roi-calculator','markup-calculator','break-even-calculator','payback-period-calculator','cac-ltv-calculator','runway-calculator'];
export default function CalculatorAeoContent({locale,tool}:{locale:Locale;tool:string}){const c=text[locale];const path=`/${locale}/${tool}`;const faq={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':c[11],'acceptedAnswer':{'@type':'Answer','text':c[12]}},{'@type':'Question','name':c[13],'acceptedAnswer':{'@type':'Answer','text':c[14]}}]};return <section className="content" aria-label={c[1]}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faq)}}/><h2>{c[0]}</h2><p>{c[7]}</p><h2>{c[1]}</h2><p><strong>{formulas[tool]||'Result = inputs processed by the calculator methodology'}</strong></p><h2>{c[2]}</h2><p>{c[8]}</p><h2>{c[3]}</h2><p>{c[9]}</p><h2>{c[4]}</h2><p>{c[10]}</p><h2>{c[5]}</h2><h3>{c[11]}</h3><p>{c[12]}</p><h3>{c[13]}</h3><p>{c[14]}</p><h2>{c[6]}</h2><p>{related.filter(x=>x!==tool).slice(0,4).map((slug,i)=><span key={slug}>{i?' · ':''}<Link href={`/${locale}/${slug}`}>{slug.replace(/-/g,' ')}</Link></span>)}</p><p><small>Canonical source: <Link href={path}>{base+path}</Link></small></p></section>}
