import Link from 'next/link';
const D:any={
'es-mx':{title:'Entiende la regla. Haz el cálculo. Toma la decisión.',lead:'Guías prácticas para precios, rentabilidad, trabajo independiente y decisiones empresariales en México.',source:'/es-mx/sources-2026',sourceLabel:'Fuentes fiscales oficiales 2026',tax:'/es-mx/tax-calculator',taxLabel:'Impuestos 2026',home:'/es-mx',open:'Abrir calculadoras',browse:'EXPLORAR POR TEMA',choose:'Elige lo que necesitas resolver.',examples:'Ejemplos prácticos',free:'Calculadoras gratuitas',nosign:'Sin registro',small:'Pensado para pequeños negocios',guides:'Guías prácticas',tools:'Calculadoras interactivas',topics:'Temas de negocio',account:'Cuenta requerida',read:'Abrir →',sponsor:'PARA MARCAS Y SOCIOS',sTitle:'Llega a lectores que están tomando decisiones de negocio.'},
'es-cl':{title:'Entiende la regla. Haz el cálculo. Toma la decisión.',lead:'Guías prácticas para precios, rentabilidad, trabajo independiente y decisiones empresariales en Chile.',source:'/es-cl/sources-2026',sourceLabel:'Fuentes tributarias oficiales 2026',tax:'/es-cl/tax-calculator',taxLabel:'Impuestos 2026',home:'/es-cl',open:'Abrir calculadoras',browse:'EXPLORAR POR TEMA',choose:'Elige lo que necesitas resolver.',examples:'Ejemplos prácticos',free:'Calculadoras gratuitas',nosign:'Sin registro',small:'Pensado para pequeños negocios',guides:'Guías prácticas',tools:'Calculadoras interactivas',topics:'Temas de negocio',account:'Cuenta requerida',read:'Abrir →',sponsor:'PARA MARCAS Y SOCIOS',sTitle:'Llega a lectores que están tomando decisiones de negocio.'},
'de-de':{title:'Regel verstehen. Berechnen. Besser entscheiden.',lead:'Praxisnahe Ratgeber zu Preisen, Rentabilität, Selbstständigkeit und Unternehmensplanung in Deutschland.',source:'/de-de/sources-2026',sourceLabel:'Offizielle Steuerquellen 2026',tax:'/de-de/tax-calculator',taxLabel:'Steuern 2026',home:'/de-de',open:'Rechner öffnen',browse:'NACH THEMA ENTDECKEN',choose:'Wählen Sie, was Sie lösen möchten.',examples:'Praxisbeispiele',free:'Kostenlose Rechner',nosign:'Keine Anmeldung',small:'Für kleine Unternehmen',guides:'Praxisratgeber',tools:'Interaktive Rechner',topics:'Geschäftsthemen',account:'Konto erforderlich',read:'Öffnen →',sponsor:'FÜR MARKEN & PARTNER',sTitle:'Erreichen Sie Leser, die aktiv Geschäftsentscheidungen recherchieren.'},
'en-in':{title:'Learn the rule. Run the calculation. Make the decision.',lead:'Practical guides for pricing, profitability, freelancing and business planning in India.',source:'/en-in/sources-2026',sourceLabel:'Official tax sources 2026–27',tax:'/en-in/tax-calculator',taxLabel:'Tax 2026–27',home:'/en-in',open:'Open calculators',browse:'EXPLORE BY TOPIC',choose:'Choose what you need to solve.',examples:'Practical examples',free:'Free calculators',nosign:'No signup',small:'Built for small business',guides:'Practical guides',tools:'Interactive calculators',topics:'Core business topics',account:'Account required',read:'Open →',sponsor:'FOR BRANDS & PARTNERS',sTitle:'Reach readers actively researching business decisions.'},
'ja-jp':{title:'ルールを理解し、計算し、より良い意思決定を。',lead:'価格設定、収益性、フリーランス、事業計画に役立つ実用ガイドです。',source:'/ja-jp/sources-2026',sourceLabel:'2026年 公式税務情報源',tax:'/ja-jp/tax-calculator',taxLabel:'税金 2026',home:'/ja-jp',open:'計算ツールを開く',browse:'テーマから探す',choose:'解決したいテーマを選択してください。',examples:'実用例',free:'無料計算ツール',nosign:'登録不要',small:'中小企業向け',guides:'実用ガイド',tools:'インタラクティブ計算',topics:'ビジネステーマ',account:'アカウント不要',read:'開く →',sponsor:'ブランド・パートナー向け',sTitle:'ビジネス判断を調べている読者にリーチ。'},
'en-gb':{title:'Learn the rule. Run the calculation. Make the decision.',lead:'Practical guides for pricing, profitability, freelancing and business planning in the UK.',source:'/en-gb/sources-2026',sourceLabel:'Official UK tax sources 2026/27',tax:'/en-gb/tax-calculator',taxLabel:'Tax 2026/27',home:'/en-gb',open:'Open calculators',browse:'EXPLORE BY TOPIC',choose:'Choose what you need to solve.',examples:'Practical examples',free:'Free calculators',nosign:'No signup',small:'Built for small business',guides:'Practical guides',tools:'Interactive calculators',topics:'Core business topics',account:'Account required',read:'Open →',sponsor:'FOR BRANDS & PARTNERS',sTitle:'Reach readers actively researching business decisions.'}};
const N:any={
'es-mx':['Markup','Precio de venta','ROI','Punto de equilibrio','Payback','CAC & LTV','Runway','Tarifa freelancer','Proyecto cerrado','Tarifa por proyecto','Descuento y margen','Freelancer vs salario'],
'es-cl':['Markup','Precio de venta','ROI','Punto de equilibrio','Payback','CAC & LTV','Runway','Tarifa freelancer','Proyecto cerrado','Tarifa por proyecto','Descuento y margen','Freelancer vs sueldo'],
'de-de':['Aufschlag','Verkaufspreis','ROI','Break-even','Amortisation','CAC & LTV','Runway','Freelancer-Stundensatz','Festpreis-Projekt','Projekt-Stundensatz','Rabatt & Marge','Freelance vs Gehalt'],
'en-in':['Markup','Selling price','ROI','Break-even','Payback','CAC & LTV','Runway','Freelance rates','Fixed projects','Project rates','Discount & margin','Freelance vs salary'],
'ja-jp':['マークアップ','販売価格','ROI','損益分岐点','投資回収期間','CAC・LTV','資金ランウェイ','フリーランス料金','固定価格プロジェクト','プロジェクト時給','割引・利益率','フリーランス vs 給与'],
'en-gb':['Markup','Selling price','ROI','Break-even','Payback','CAC & LTV','Runway','Freelance rates','Fixed projects','Project rates','Discount & margin','Freelance vs salary']};
const S=['markup-calculator','selling-price-calculator','roi-calculator','break-even-calculator','payback-period-calculator','cac-ltv-calculator','runway-calculator','freelance-rate-calculator','fixed-project-price-calculator','project-hourly-rate-calculator','discount-margin-calculator','freelance-vs-salary-calculator'];
export default function CountryGuides({market}:{market:string}){const d=D[market];const ui:any=market.startsWith('es-')?{tax:'Impuesto',tag:'NEGOCIOS'}:market==='de-de'?{tax:'Steuer',tag:'GESCHÄFT'}:market==='ja-jp'?{tax:'税',tag:'ビジネス'}:{tax:'Tax',tag:'BUSINESS'};const advertise=market==='pt-br'?'/pt-br/anuncie':'/'+market+'/advertise';const guides=S.map((s,i)=>['/'+market+'/'+s,i===0?'%':i===1?'$':i===2?'↗':i===3?'◎':i===4?'↻':i===5?'×':i===6?'◷':i===7?'$':i===8?'▣':i===9?'⌁':i===10?'%':'↔',N[market][i]]);guides.push([d.tax,ui.tax,d.taxLabel]);return <main className="shell"><section className="hero heroCompact"><p className="eyebrow">BUSINESS CALCULATOR HUB</p><h1>{d.title}</h1><p className="lead">{d.lead}</p><div className="heroActions"><a className="primary" href="#all-guides">{d.browse} →</a><Link className="secondary" href={d.home+'#calculators'}>{d.open}</Link><Link className="secondary" href={d.source}>{d.sourceLabel}</Link></div><div className="trustRow"><span>✓ {d.examples}</span><span>✓ {d.free}</span><span>✓ {d.nosign}</span><span>✓ {d.small}</span></div></section><section className="valueStrip"><div><strong>13+</strong><span>{d.guides}</span></div><div><strong>14</strong><span>{d.tools}</span></div><div><strong>4</strong><span>{d.topics}</span></div><div><strong>0</strong><span>{d.account}</span></div></section><section id="all-guides" className="sectionBlock"><div className="sectionHeading"><div><p className="eyebrow">{d.browse}</p><h2>{d.choose}</h2></div><p>{d.lead}</p></div><div className="guideGrid">{guides.map((g:any)=><Link className="guideCard" href={g[0]} key={g[0]}><span className="toolIcon">{g[1]}</span><span className="tag" style={{display:'block',marginTop:18}}>{ui.tag}</span><h2>{g[2]}</h2><p>{d.lead}</p><strong>{d.read}</strong></Link>)}</div></section><section className="sponsorCallout"><div><span className="sponsorLabel">{d.sponsor}</span><h2>{d.sTitle}</h2><p>{d.lead}</p></div><Link className="primary" href={advertise}>{d.sponsor} →</Link></section></main>}