import Link from 'next/link';import s from '../home.module.css';
export type MarketKey='pt-br'|'es-mx'|'es-cl'|'de-de'|'en-in'|'ja-jp'|'en-gb';
const D:any={
'pt-br':{title:'Calculadoras inteligentes',blue:'para decisões de negócio mais inteligentes',lead:'Ferramentas poderosas, gratuitas e fáceis de usar para planejar, investir, crescer e ter sucesso.',calc:'Calculadora de Margem de Lucro',rev:'Receita',cost:'Custos',margin:'Margem de Lucro',v1:'R$ 10.000,00',v2:'R$ 6.500,00',free:'100% Grátis',accurate:'Precisas',fast:'Rápidas e fáceis',explore:'Ver Calculadoras →',guides:'Ver Guias',guide:'/pt-br/guias',advertise:'/pt-br/anuncie',ad:'ANUNCIE NO HUB',source:'/pt-br/fontes-2026',sourceLabel:'Fontes oficiais',tax:'/pt-br/calculadora-simples-nacional',taxLabel:'Simples Nacional 2026'},
'es-mx':{title:'Calculadoras inteligentes',blue:'para decisiones de negocio más inteligentes',lead:'Herramientas potentes, gratuitas y fáciles de usar para planificar, invertir, crecer y tener éxito.',calc:'Calculadora de Margen de Ganancia',rev:'Ingresos',cost:'Costos',margin:'Margen de Ganancia',v1:'$ 10,000',v2:'$ 6,500',free:'100% Gratis',accurate:'Precisas',fast:'Rápidas y fáciles',explore:'Ver Calculadoras →',guides:'Ver Guías',guide:'/es-mx/guides',advertise:'/es-mx/advertise',ad:'ANUNCIAR EN EL HUB',source:'/es-mx/sources-2026',sourceLabel:'Fuentes oficiales',tax:'/es-mx/tax-calculator',taxLabel:'Impuestos 2026'},
'es-cl':{title:'Calculadoras inteligentes',blue:'para decisiones de negocio más inteligentes',lead:'Herramientas potentes, gratuitas y fáciles de usar para planificar, invertir, crecer y tener éxito.',calc:'Calculadora de Margen de Ganancia',rev:'Ingresos',cost:'Costos',margin:'Margen de Ganancia',v1:'$ 10.000.000',v2:'$ 6.500.000',free:'100% Gratis',accurate:'Precisas',fast:'Rápidas y fáciles',explore:'Ver Calculadoras →',guides:'Ver Guías',guide:'/es-cl/guides',advertise:'/es-cl/advertise',ad:'ANUNCIAR EN EL HUB',source:'/es-cl/sources-2026',sourceLabel:'Fuentes oficiales',tax:'/es-cl/tax-calculator',taxLabel:'Impuestos 2026'},
'de-de':{title:'Intelligente Rechner',blue:'für intelligentere Geschäftsentscheidungen',lead:'Leistungsstarke, kostenlose und einfach zu bedienende Rechner zum Planen, Investieren und Wachsen.',calc:'Gewinnmargen-Rechner',rev:'Umsatz',cost:'Kosten',margin:'Gewinnmarge',v1:'€ 10.000',v2:'€ 6.500',free:'100% Kostenlos',accurate:'Genau',fast:'Schnell & einfach',explore:'Rechner entdecken →',guides:'Ratgeber ansehen',guide:'/de-de/guides',advertise:'/de-de/advertise',ad:'BEI UNS WERBEN',source:'/de-de/sources-2026',sourceLabel:'Offizielle Quellen',tax:'/de-de/tax-calculator',taxLabel:'Steuern 2026'},
'en-in':{title:'Smart Calculators',blue:'for Smarter Business Decisions',lead:'Powerful, free and easy-to-use calculators to help you plan, invest, grow and succeed.',calc:'Profit Margin Calculator',rev:'Revenue',cost:'Costs',margin:'Profit Margin',v1:'₹ 10,000',v2:'₹ 6,500',free:'100% Free',accurate:'Accurate',fast:'Fast & Easy',explore:'Explore Calculators →',guides:'Browse Guides',guide:'/en-in/guides',advertise:'/en-in/advertise',ad:'ADVERTISE WITH US',source:'/en-in/sources-2026',sourceLabel:'Official sources',tax:'/en-in/tax-calculator',taxLabel:'Tax 2026–27'},
'ja-jp':{title:'より賢いビジネス',blue:'意思決定のためのスマート計算ツール',lead:'計画、投資、成長、成功を支援する強力で使いやすい無料の計算ツールです。',calc:'利益率計算ツール',rev:'売上',cost:'コスト',margin:'利益率',v1:'¥ 10,000',v2:'¥ 6,500',free:'100% 無料',accurate:'正確',fast:'速くて簡単',explore:'計算ツールを見る →',guides:'ガイドを見る',guide:'/ja-jp/guides',advertise:'/ja-jp/advertise',ad:'広告掲載はこちら',source:'/ja-jp/sources-2026',sourceLabel:'公式情報源',tax:'/ja-jp/tax-calculator',taxLabel:'税金 2026'},
'en-gb':{title:'Smart Calculators',blue:'for Smarter Business Decisions',lead:'Powerful, free and easy-to-use calculators to help you plan, invest, grow and succeed.',calc:'Profit Margin Calculator',rev:'Revenue',cost:'Costs',margin:'Profit Margin',v1:'£ 10,000',v2:'£ 6,500',free:'100% Free',accurate:'Accurate',fast:'Fast & Easy',explore:'Explore Calculators →',guides:'Browse Guides',guide:'/en-gb/guides',advertise:'/en-gb/advertise',ad:'ADVERTISE WITH US',source:'/en-gb/sources-2026',sourceLabel:'Official sources',tax:'/en-gb/tax-calculator',taxLabel:'Tax 2026/27'}};
const Flag=({code,name}:{code:string,name:string})=><img className={s.marketFlag} src={`https://flagcdn.com/w40/${code}.png`} alt={`Bandeira de ${name}`} loading="eager"/>;
const CARD:any={
'pt-br':[['freelance-rate-calculator','$','Valor Freelancer','Calcule seu valor hora ideal'],['roi-calculator','↗','ROI','Meça o retorno sobre investimento'],['salary-to-hourly-calculator','◉','Salário por Hora','Converta salário anual em valor hora'],['markup-calculator','▦','Markup','Defina preço a partir do custo'],['break-even-calculator','◔','Ponto de Equilíbrio','Descubra quando o negócio se paga'],['payback-period-calculator','↻','Payback','Estime o prazo de retorno'],['cac-ltv-calculator','×','CAC & LTV','Meça economia por cliente'],['runway-calculator','◷','Runway','Estime quantos meses o caixa dura'],['selling-price-calculator','$','Preço de Venda','Defina preço por custo e margem'],['discount-margin-calculator','%','Desconto e Margem','Proteja a margem ao dar desconto'],['fixed-project-price-calculator','▣','Projeto Fechado','Transforme horas em preço fechado'],['project-hourly-rate-calculator','⌁','Valor Hora de Projeto','Calcule preço por projeto'],['freelance-vs-salary-calculator','↔','Freelancer vs Salário','Compare modelos de remuneração']],
'es-mx':[['freelance-rate-calculator','$','Tarifa Freelancer','Calcula tu tarifa por hora'],['roi-calculator','↗','ROI','Mide el retorno de inversión'],['salary-to-hourly-calculator','◉','Salario por Hora','Convierte salario anual a tarifa horaria'],['markup-calculator','▦','Markup','Calcula precio desde el costo'],['break-even-calculator','◔','Punto de Equilibrio','Encuentra el nivel mínimo de ventas'],['payback-period-calculator','↻','Payback','Estima el plazo de recuperación'],['cac-ltv-calculator','×','CAC & LTV','Mide economía por cliente'],['runway-calculator','◷','Runway','Estima cuántos meses dura la caja'],['selling-price-calculator','$','Precio de Venta','Define precio por costo y margen'],['discount-margin-calculator','%','Descuento y Margen','Protege el margen al descontar'],['fixed-project-price-calculator','▣','Proyecto Cerrado','Convierte horas en precio fijo'],['project-hourly-rate-calculator','⌁','Tarifa por Proyecto','Calcula tarifa por hora'],['freelance-vs-salary-calculator','↔','Freelancer vs Salario','Compara modelos de remuneración']],
'es-cl':[['freelance-rate-calculator','$','Tarifa Freelancer','Calcula tu tarifa por hora'],['roi-calculator','↗','ROI','Mide el retorno de inversión'],['salary-to-hourly-calculator','◉','Sueldo por Hora','Convierte sueldo anual a tarifa horaria'],['markup-calculator','▦','Markup','Calcula precio desde el costo'],['break-even-calculator','◔','Punto de Equilibrio','Encuentra el nivel mínimo de ventas'],['payback-period-calculator','↻','Payback','Estima el plazo de recuperación'],['cac-ltv-calculator','×','CAC & LTV','Mide economía por cliente'],['runway-calculator','◷','Runway','Estima cuántos meses dura la caja'],['selling-price-calculator','$','Precio de Venta','Define precio por costo y margen'],['discount-margin-calculator','%','Descuento y Margen','Protege el margen al descontar'],['fixed-project-price-calculator','▣','Proyecto Cerrado','Convierte horas en precio fijo'],['project-hourly-rate-calculator','⌁','Tarifa por Proyecto','Calcula tarifa por hora'],['freelance-vs-salary-calculator','↔','Freelancer vs Sueldo','Compara modelos de remuneración']],
'de-de':[['freelance-rate-calculator','$','Freelancer-Stundensatz','Idealen Stundensatz berechnen'],['roi-calculator','↗','ROI','Investitionsrendite messen'],['salary-to-hourly-calculator','◉','Gehalt pro Stunde','Jahresgehalt in Stundenlohn umrechnen'],['markup-calculator','▦','Aufschlag','Verkaufspreis aus Kosten berechnen'],['break-even-calculator','◔','Break-even','Mindestabsatz ermitteln'],['payback-period-calculator','↻','Amortisation','Rückzahlungsdauer schätzen'],['cac-ltv-calculator','×','CAC & LTV','Kundenökonomie messen'],['runway-calculator','◷','Runway','Cash-Reichweite in Monaten'],['selling-price-calculator','$','Verkaufspreis','Preis aus Kosten und Marge'],['discount-margin-calculator','%','Rabatt & Marge','Marge bei Rabatten schützen'],['fixed-project-price-calculator','▣','Festpreis-Projekt','Stunden in Festpreis umwandeln'],['project-hourly-rate-calculator','⌁','Projekt-Stundensatz','Projektpreis kalkulieren'],['freelance-vs-salary-calculator','↔','Freelance vs Gehalt','Vergütungsmodelle vergleichen']],
'en-in':[['freelance-rate-calculator','$','Freelance Rate Calculator','Calculate your ideal hourly rate'],['roi-calculator','↗','ROI Calculator','Measure return on investment'],['salary-to-hourly-calculator','◉','Salary to Hourly','Convert annual salary to hourly pay'],['markup-calculator','▦','Markup Calculator','Estimate selling price from cost'],['break-even-calculator','◔','Break-even Calculator','Find your break-even point'],['payback-period-calculator','↻','Payback Period','Estimate investment recovery time'],['cac-ltv-calculator','×','CAC & LTV','Measure customer economics'],['runway-calculator','◷','Business Runway','Estimate how long cash will last'],['selling-price-calculator','$','Selling Price','Price from cost and target margin'],['discount-margin-calculator','%','Discount & Margin','Protect margin before discounting'],['fixed-project-price-calculator','▣','Fixed Project Price','Turn hours into a fixed quote'],['project-hourly-rate-calculator','⌁','Project Hourly Rate','Price project work'],['freelance-vs-salary-calculator','↔','Freelance vs Salary','Compare compensation models']],
'ja-jp':[['freelance-rate-calculator','$','フリーランス料金','理想的な時給を計算'],['roi-calculator','↗','ROI','投資収益率を計算'],['salary-to-hourly-calculator','◉','年収から時給','年収を時給に換算'],['markup-calculator','▦','マークアップ','コストから販売価格を計算'],['break-even-calculator','◔','損益分岐点','必要販売量を計算'],['payback-period-calculator','↻','投資回収期間','回収までの期間を推定'],['cac-ltv-calculator','×','CAC・LTV','顧客単位の採算を確認'],['runway-calculator','◷','資金ランウェイ','資金が何か月持つか推定'],['selling-price-calculator','$','販売価格','コストと利益率から価格設定'],['discount-margin-calculator','%','割引・利益率','割引後の利益率を保護'],['fixed-project-price-calculator','▣','固定価格プロジェクト','工数から固定価格を計算'],['project-hourly-rate-calculator','⌁','プロジェクト時給','プロジェクト料金を計算'],['freelance-vs-salary-calculator','↔','フリーランス vs 給与','報酬モデルを比較']],
'en-gb':[['freelance-rate-calculator','$','Freelance Rate Calculator','Calculate your ideal hourly rate'],['roi-calculator','↗','ROI Calculator','Measure return on investment'],['salary-to-hourly-calculator','◉','Salary to Hourly','Convert annual salary to hourly pay'],['markup-calculator','▦','Markup Calculator','Estimate selling price from cost'],['break-even-calculator','◔','Break-even Calculator','Find your break-even point'],['payback-period-calculator','↻','Payback Period','Estimate investment recovery time'],['cac-ltv-calculator','×','CAC & LTV','Measure customer economics'],['runway-calculator','◷','Business Runway','Estimate how long cash will last'],['selling-price-calculator','$','Selling Price','Price from cost and target margin'],['discount-margin-calculator','%','Discount & Margin','Protect margin before discounting'],['fixed-project-price-calculator','▣','Fixed Project Price','Turn hours into a fixed quote'],['project-hourly-rate-calculator','⌁','Project Hourly Rate','Price project work'],['freelance-vs-salary-calculator','↔','Freelance vs Salary','Compare compensation models']]};

const MARKET_LINKS=[
  ['/', 'us','United States'],
  ['/pt-br','br','Brasil'],
  ['/es-mx','mx','México'],
  ['/es-cl','cl','Chile'],
  ['/en-gb','gb','United Kingdom'],
  ['/de-de','de','Deutschland'],
  ['/en-in','in','India'],
  ['/ja-jp','jp','日本'],
] as const;

const C:any={
'pt-br':{choose:'Escolha seu mercado:',hero:'Ferramentas e guias financeiros para decisões',smart:'mais inteligentes.',sub:'100% gratuitas, baseadas nas leis e tributos do Brasil.',search:'Ex.: Salário líquido, INSS, MEI, Impostos...',free:'100% Gratuitas',freeSub:'Sem cadastro',trusted:'Confiáveis',trustedSub:'Fontes oficiais',fast:'Rápidas e fáceis',fastSub:'Resultados em segundos',featured:'Calculadoras em destaque',all:'Ver todas →',pos1:'POSIÇÃO 1',pos2:'POSIÇÃO 2',brand:'SUA MARCA AQUI',sponsor1:'Posicionamento premium para sua empresa',sponsor2:'Exposição contextual dentro do Hub Brasil',sponsorSub:'Alcance usuários em momento de decisão.',sponsorSub2:'Formatos pensados para performance e visibilidade.',learn:'Saiba Mais',plans:'Conheça os Planos',details:'Ver detalhes completos →',excellent:'Excelente',trust1:'Conteúdo confiável',trust1d:'Calculadoras e guias baseados em fontes oficiais e regras locais.',trust2:'Atualizado sempre',trust2d:'Informações revisadas periodicamente para garantir precisão e relevância.',trust3:'100% gratuito',trust3d:'Acesso ilimitado às ferramentas e guias do Business Calculator Hub.',trust4:'Privacidade e segurança',trust4d:'Navegação segura e sem coleta desnecessária de dados pessoais.',allTitle:'Todas as calculadoras'},
'es-mx':{choose:'Elige tu mercado:',hero:'Herramientas y guías financieras para decisiones',smart:'más inteligentes.',sub:'100% gratuitas y adaptadas al mercado de México.',search:'Ej.: impuestos, ROI, freelance, margen...',free:'100% Gratis',freeSub:'Sin registro',trusted:'Confiables',trustedSub:'Fuentes oficiales',fast:'Rápidas y fáciles',fastSub:'Resultados en segundos',featured:'Calculadoras destacadas',all:'Ver todas →',pos1:'POSICIÓN 1',pos2:'POSICIÓN 2',brand:'TU MARCA AQUÍ',sponsor1:'Posicionamiento premium para tu empresa',sponsor2:'Exposición contextual dentro del Hub México',sponsorSub:'Llega a usuarios en el momento de decisión.',sponsorSub2:'Formatos pensados para rendimiento y visibilidad.',learn:'Saber más',plans:'Ver planes',details:'Ver detalles →',excellent:'Excelente',trust1:'Contenido confiable',trust1d:'Calculadoras y guías basadas en fuentes oficiales y reglas locales.',trust2:'Siempre actualizado',trust2d:'Información revisada periódicamente para mantener precisión y relevancia.',trust3:'100% gratuito',trust3d:'Acceso ilimitado a las herramientas y guías del Hub.',trust4:'Privacidad y seguridad',trust4d:'Navegación segura y sin recolección innecesaria de datos personales.',allTitle:'Todas las calculadoras'},
'es-cl':{choose:'Elige tu mercado:',hero:'Herramientas y guías financieras para decisiones',smart:'más inteligentes.',sub:'100% gratuitas y adaptadas al mercado de Chile.',search:'Ej.: impuestos, ROI, freelance, margen...',free:'100% Gratis',freeSub:'Sin registro',trusted:'Confiables',trustedSub:'Fuentes oficiales',fast:'Rápidas y fáciles',fastSub:'Resultados en segundos',featured:'Calculadoras destacadas',all:'Ver todas →',pos1:'POSICIÓN 1',pos2:'POSICIÓN 2',brand:'TU MARCA AQUÍ',sponsor1:'Posicionamiento premium para tu empresa',sponsor2:'Exposición contextual dentro del Hub Chile',sponsorSub:'Llega a usuarios en el momento de decisión.',sponsorSub2:'Formatos pensados para rendimiento y visibilidad.',learn:'Saber más',plans:'Ver planes',details:'Ver detalles →',excellent:'Excelente',trust1:'Contenido confiable',trust1d:'Calculadoras y guías basadas en fuentes oficiales y reglas locales.',trust2:'Siempre actualizado',trust2d:'Información revisada periódicamente para mantener precisión y relevancia.',trust3:'100% gratuito',trust3d:'Acceso ilimitado a las herramientas y guías del Hub.',trust4:'Privacidad y seguridad',trust4d:'Navegación segura y sin recolección innecesaria de datos personales.',allTitle:'Todas las calculadoras'},
'de-de':{choose:'Markt auswählen:',hero:'Finanzrechner und Ratgeber für',smart:'klügere Entscheidungen.',sub:'100% kostenlos und auf Deutschland zugeschnitten.',search:'Z. B. Steuern, ROI, Freelancer, Marge...',free:'100% Kostenlos',freeSub:'Ohne Anmeldung',trusted:'Verlässlich',trustedSub:'Offizielle Quellen',fast:'Schnell & einfach',fastSub:'Ergebnisse in Sekunden',featured:'Beliebte Rechner',all:'Alle ansehen →',pos1:'POSITION 1',pos2:'POSITION 2',brand:'IHRE MARKE HIER',sponsor1:'Premium-Platzierung für Ihr Unternehmen',sponsor2:'Kontextuelle Sichtbarkeit im Deutschland-Hub',sponsorSub:'Erreichen Sie Nutzer im Entscheidungsprozess.',sponsorSub2:'Formate für Sichtbarkeit und Performance.',learn:'Mehr erfahren',plans:'Pläne ansehen',details:'Details ansehen →',excellent:'Sehr gut',trust1:'Verlässliche Inhalte',trust1d:'Rechner und Ratgeber auf Basis offizieller Quellen und lokaler Regeln.',trust2:'Regelmäßig aktualisiert',trust2d:'Informationen werden laufend auf Genauigkeit und Relevanz geprüft.',trust3:'100% kostenlos',trust3d:'Unbegrenzter Zugriff auf Tools und Ratgeber.',trust4:'Datenschutz & Sicherheit',trust4d:'Sichere Nutzung ohne unnötige Erfassung persönlicher Daten.',allTitle:'Alle Rechner'},
'en-in':{choose:'Choose your market:',hero:'Financial tools and guides for',smart:'smarter decisions.',sub:'100% free and tailored for the India market.',search:'e.g. tax, ROI, freelance, margin...',free:'100% Free',freeSub:'No sign-up',trusted:'Reliable',trustedSub:'Official sources',fast:'Fast & easy',fastSub:'Results in seconds',featured:'Featured calculators',all:'View all →',pos1:'POSITION 1',pos2:'POSITION 2',brand:'YOUR BRAND HERE',sponsor1:'Premium placement for your company',sponsor2:'Contextual exposure inside the India Hub',sponsorSub:'Reach users at the moment of decision.',sponsorSub2:'Formats designed for visibility and performance.',learn:'Learn More',plans:'View Plans',details:'View details →',excellent:'Excellent',trust1:'Trusted content',trust1d:'Calculators and guides based on official sources and local rules.',trust2:'Always updated',trust2d:'Information reviewed regularly for accuracy and relevance.',trust3:'100% free',trust3d:'Unlimited access to Business Calculator Hub tools and guides.',trust4:'Privacy & security',trust4d:'Secure browsing without unnecessary personal-data collection.',allTitle:'All calculators'},
'en-gb':{choose:'Choose your market:',hero:'Financial tools and guides for',smart:'smarter decisions.',sub:'100% free and tailored for the UK market.',search:'e.g. tax, ROI, freelance, margin...',free:'100% Free',freeSub:'No sign-up',trusted:'Reliable',trustedSub:'Official sources',fast:'Fast & easy',fastSub:'Results in seconds',featured:'Featured calculators',all:'View all →',pos1:'POSITION 1',pos2:'POSITION 2',brand:'YOUR BRAND HERE',sponsor1:'Premium placement for your company',sponsor2:'Contextual exposure inside the UK Hub',sponsorSub:'Reach users at the moment of decision.',sponsorSub2:'Formats designed for visibility and performance.',learn:'Learn More',plans:'View Plans',details:'View details →',excellent:'Excellent',trust1:'Trusted content',trust1d:'Calculators and guides based on official sources and local rules.',trust2:'Always updated',trust2d:'Information reviewed regularly for accuracy and relevance.',trust3:'100% free',trust3d:'Unlimited access to Business Calculator Hub tools and guides.',trust4:'Privacy & security',trust4d:'Secure browsing without unnecessary personal-data collection.',allTitle:'All calculators'},
'ja-jp':{choose:'市場を選択:',hero:'より良い意思決定のための',smart:'金融ツールとガイド。',sub:'日本市場向けに最適化された100%無料のツールです。',search:'例：税金、ROI、フリーランス、利益率...',free:'100% 無料',freeSub:'登録不要',trusted:'信頼できる',trustedSub:'公式情報源',fast:'速くて簡単',fastSub:'数秒で結果',featured:'注目の計算ツール',all:'すべて見る →',pos1:'掲載枠 1',pos2:'掲載枠 2',brand:'あなたのブランド',sponsor1:'企業向けプレミアム掲載',sponsor2:'日本ハブ内の文脈型プロモーション',sponsorSub:'意思決定中のユーザーにリーチできます。',sponsorSub2:'視認性と成果を意識したフォーマットです。',learn:'詳しく見る',plans:'プランを見る',details:'詳細を見る →',excellent:'良好',trust1:'信頼できるコンテンツ',trust1d:'公式情報源と国内ルールに基づく計算ツールとガイド。',trust2:'継続的に更新',trust2d:'正確性と関連性を保つため定期的に見直しています。',trust3:'100% 無料',trust3d:'Business Calculator Hubのツールとガイドを無制限で利用できます。',trust4:'プライバシーと安全性',trust4d:'不要な個人情報を収集せず、安全に利用できます。',allTitle:'すべての計算ツール'}};

const MARKET_KEY_TO_HREF:any={'pt-br':'/pt-br','es-mx':'/es-mx','es-cl':'/es-cl','de-de':'/de-de','en-in':'/en-in','ja-jp':'/ja-jp','en-gb':'/en-gb'};

export default function CountryHome({market}:{market:MarketKey}){
  const d=D[market],c=C[market],cards=[...CARD[market],[d.tax,'Tax',d.taxLabel,d.sourceLabel]];
  const featured=cards.slice(0,4);
  const active=MARKET_KEY_TO_HREF[market];
  const marketName=MARKET_LINKS.find(x=>x[0]===active)?.[2]||'Market';
  const taxHref=d.tax;
  return <main className={s.page}>
    <div className={s.brMarketBar}><span>{c.choose}</span>{MARKET_LINKS.map(([href,code,name])=><Link key={href} href={href} className={href===active?s.activeMarket:undefined}><Flag code={code} name={name}/>{name}</Link>)}<Link href="/">🌐 Global →</Link></div>
    <div className={s.brWrap}>
      <section className={s.brHero}>
        <div className={s.brHeroCopy}><h1>{c.hero} <span>{c.smart}</span></h1><p>{c.sub}</p><div className={s.brSearch}><span>{c.search}</span><a href="#calculators" aria-label={c.featured}>⌕</a></div><div className={s.brBenefits}><div><b>⚡</b><span><strong>{c.free}</strong><small>{c.freeSub}</small></span></div><div><b>✓</b><span><strong>{c.trusted}</strong><small>{c.trustedSub}</small></span></div><div><b>◷</b><span><strong>{c.fast}</strong><small>{c.fastSub}</small></span></div></div></div>
        <div className={s.brCalcVisual}><div className={s.brCalcCard}><h3>{d.calc}</h3><label>{d.rev}<div>{d.v1}</div></label><label>{d.cost}<div>{d.v2}</div></label><span>{d.margin}</span><strong>35.00%</strong><em>{c.excellent}</em><Link href={taxHref}>{c.details}</Link></div><div className={s.brChart}><span>↗</span><div className={s.brBars}><i/><i/><i/></div><div className={s.brPie}/></div></div>
      </section>
      <Link href={d.advertise} className={s.brSponsor}><b>{c.pos1}</b><span className={s.brSponsorLogo}>☁ <strong>{c.brand}</strong></span><span><strong>{c.sponsor1}</strong><small>{c.sponsorSub}</small></span><span className={s.brSponsorButton}>{c.learn}</span></Link>
      <section className={s.brFeatured} id="calculators"><div className={s.brSectionHead}><h2>{c.featured}</h2><a href="#all-calculators">{c.all}</a></div><div className={s.brFeaturedGrid}>{featured.map((x:any)=><Link key={x[0]} href={x[0].startsWith('/')?x[0]:'/'+market+'/'+x[0]}><b>{x[1]}</b><strong>{x[2]}</strong><span>{x[3]}</span><small><Flag code={MARKET_LINKS.find(m=>m[0]===active)?.[1]||'us'} name={marketName}/> {marketName}</small></Link>)}</div></section>
      <Link href={d.advertise} className={s.brSponsor}><b>{c.pos2}</b><span className={s.brSponsorLogo}>☁ <strong>{c.brand}</strong></span><span><strong>{c.sponsor2}</strong><small>{c.sponsorSub2}</small></span><span className={s.brSponsorButton}>{c.plans}</span></Link>
      <section className={s.brTrust} id="sobre"><div><b>♢</b><strong>{c.trust1}</strong><span>{c.trust1d}</span></div><div><b>◎</b><strong>{c.trust2}</strong><span>{c.trust2d}</span></div><div><b>▥</b><strong>{c.trust3}</strong><span>{c.trust3d}</span></div><div><b>▣</b><strong>{c.trust4}</strong><span>{c.trust4d}</span></div></section>
      <section className={s.popular} id="all-calculators"><div className={s.popularHead}><h2>{c.allTitle}</h2></div><div className={s.cards}>{cards.map((x:any)=><Link href={x[0].startsWith('/')?x[0]:'/'+market+'/'+x[0]} className={s.card} key={x[0]}><span className={s.cardIcon}>{x[1]}</span><span><strong>{x[2]}</strong><span>{x[3]}</span></span></Link>)}</div></section>
    </div>
    <div className={s.brMarketFooter}><span>{c.choose}</span>{MARKET_LINKS.map(([href,code,name])=><Link key={href} href={href}><Flag code={code} name={name}/>{name}</Link>)}<Link href="/">🌐 Global →</Link></div>
  </main>
}
