import Link from 'next/link';
import s from './home.module.css';

const Flag=({code,name}:{code:string,name:string})=><img className={s.marketFlag} src={'https://flagcdn.com/w40/'+code+'.png'} alt={'Flag of '+name} loading="eager"/>;
const markets=[['/','us','United States'],['/pt-br','br','Brazil'],['/es-mx','mx','Mexico'],['/es-cl','cl','Chile'],['/en-gb','gb','United Kingdom'],['/de-de','de','Germany'],['/en-in','in','India'],['/ja-jp','jp','Japan']] as const;
const cards=[
['/freelance-rate-calculator','$','Freelance Rate Calculator','Find a sustainable hourly rate from income, costs, taxes and billable time'],
['/fixed-project-price-calculator','◎','Fixed Project Price Calculator','Turn your rate and scope into a project price'],
['/project-hourly-rate-calculator','◷','Project Hourly Rate Calculator','Estimate the effective hourly value of a project'],
['/freelance-vs-salary-calculator','↔','Freelance vs Salary Calculator','Compare independent work with salaried compensation'],
['/salary-to-hourly-calculator','◉','Salary to Hourly Calculator','Convert annual salary to an hourly equivalent'],
['/profit-margin-calculator','%','Profit Margin Calculator','Protect margin before quoting a client'],
['/markup-calculator','▦','Markup Calculator','Build a selling price from cost and markup'],
['/break-even-calculator','◔','Break-Even Calculator','Know how much work or revenue you need to break even']
];
export default function Home(){return <main className={s.page}>
  <div className={s.brMarketBar}><span>Choose your market:</span>{markets.map(([href,code,name])=><Link key={href} href={href} className={href==='/'?s.activeMarket:undefined}><Flag code={code} name={name}/>{name}</Link>)}</div>
  <div className={s.brWrap}>
    <section className={s.brHero}><div className={s.brHeroCopy}><p className={s.kicker}>PRICING & MONEY TOOLS FOR INDEPENDENT PROFESSIONALS</p><h1>Know what to charge. <span>Protect your income.</span></h1><p>Free calculators and practical guides for freelancers, consultants and small service businesses making pricing, salary and profitability decisions.</p><div className={s.actions}><Link className={s.primary} href="/freelance-rate-calculator">Calculate my freelance rate →</Link><Link className={s.secondary} href="/guides/how-much-should-i-charge-as-a-freelancer">How much should I charge?</Link></div><div className={s.brBenefits}><div><b>⚡</b><span><strong>100% Free</strong><small>No sign-up</small></span></div><div><b>✓</b><span><strong>Decision-focused</strong><small>Useful before you quote</small></span></div><div><b>◷</b><span><strong>Fast</strong><small>Results in seconds</small></span></div></div></div><div className={s.brCalcVisual}><div className={s.brCalcCard}><h3>Freelance Rate Calculator</h3><label>Income target<div>$ 80,000</div></label><label>Business costs<div>$ 12,000</div></label><span>Recommended rate</span><strong>$88.46/hr</strong><em>Built around billable time</em><Link href="/freelance-rate-calculator">Calculate your rate →</Link></div><div className={s.brChart}><span>↗</span><div className={s.brBars}><i/><i/><i/></div><div className={s.brPie}/></div></div></section>
    <Link href="/advertise" className={s.brSponsor}><b>PARTNER SLOT</b><span className={s.brSponsorLogo}>☁ <strong>YOUR BRAND HERE</strong></span><span><strong>Reach users while they make pricing and business decisions</strong><small>Contextual placement for software, finance, invoicing, CRM and productivity brands.</small></span><span className={s.brSponsorButton}>Sponsor this audience</span></Link>
    <section className={s.brFeatured} id="calculators"><div className={s.brSectionHead}><h2>Start with pricing</h2><a href="#all-calculators">View all tools →</a></div><div className={s.brFeaturedGrid}>{cards.slice(0,4).map(x=><Link key={x[0]} href={x[0]}><b>{x[1]}</b><strong>{x[2]}</strong><span>{x[3]}</span><small>🌐 Global</small></Link>)}</div></section>
    <section className={s.brTrust}><div><b>♢</b><strong>Built for decisions</strong><span>Tools connect income goals, costs, time and pricing.</span></div><div><b>◎</b><strong>Useful before you quote</strong><span>Compare hourly, project and salary scenarios.</span></div><div><b>▥</b><strong>100% free</strong><span>Unlimited access without mandatory registration.</span></div><div><b>▣</b><strong>Commercially relevant audience</strong><span>Freelancers and small businesses actively evaluating what to charge and which tools to use.</span></div></section>
    <section className={s.popular} id="all-calculators"><div className={s.popularHead}><h2>Pricing & business calculators</h2></div><div className={s.cards}>{cards.map(x=><Link href={x[0]} className={s.card} key={x[0]}><span className={s.cardIcon}>{x[1]}</span><span><strong>{x[2]}</strong><span>{x[3]}</span></span></Link>)}</div></section>
  </div>
  <div className={s.brMarketFooter}><span>Choose your market:</span>{markets.map(([href,code,name])=><Link key={href} href={href}><Flag code={code} name={name}/>{name}</Link>)}</div>
</main>}