import type { Metadata } from 'next';import Link from 'next/link';
export const metadata:Metadata={title:'Business Guides, Freelance Tips & Financial Formulas',description:'Practical business guides covering profit margin, break-even, freelance pricing, salary conversion, markup and AI tools.',alternates:{canonical:'/guides'}};
const guides=[
{href:'/guides/how-much-should-i-charge-as-a-freelancer',tag:'Freelancing',title:'How Much Should I Charge as a Freelancer?',text:'Set a sustainable baseline using income goals, expenses and billable hours.'},
{href:'/guides/what-is-a-good-profit-margin',tag:'Profitability',title:'What Is a Good Profit Margin?',text:'Learn why healthy margins vary and how to evaluate your own trend.'},
{href:'/guides/how-to-calculate-markup-from-cost',tag:'Pricing',title:'How to Calculate Markup From Cost',text:'Turn cost and markup into selling price and understand markup versus margin.'},
{href:'/guides/how-to-calculate-profit-margin',tag:'Profitability',title:'How to Calculate Profit Margin',text:'Formula, examples and a direct path to the free margin calculator.'},
{href:'/guides/how-to-calculate-break-even-point',tag:'Planning',title:'How to Calculate Break-Even Point',text:'Understand contribution margin and estimate the sales volume needed to cover costs.'},
{href:'/guides/freelance-hourly-rate',tag:'Freelancing',title:'How to Calculate Your Freelance Hourly Rate',text:'Build a sustainable rate around income goals, expenses and realistic billable hours.'},
{href:'/guides/salary-to-hourly-rate',tag:'Compensation',title:'Salary to Hourly Rate',text:'Convert annual salary into an hourly equivalent and compare compensation more clearly.'},
{href:'/guides/25-an-hour-is-how-much-a-year',tag:'Pay Breakdown',title:'$25 an Hour Is How Much a Year?',text:'Annual, monthly, weekly and daily breakdown with an interactive conversion tool.'},
{href:'/guides/30-an-hour-is-how-much-a-year',tag:'Pay Breakdown',title:'$30 an Hour Is How Much a Year?',text:'See the annual equivalent and calculate a different schedule in seconds.'},
{href:'/ai-tools/best-ai-tools-for-small-business',tag:'AI & Software',title:'Best AI Tools for Small Business',text:'A growing buyer guide for automation, productivity and business operations.'},
{href:'/ai-tools/creao',tag:'AI Review',title:'CREAO AI Review',text:'A practical look at CREAO for businesses exploring AI-powered workflows.'}];
export default function GuidesPage(){return <main className="shell"><header className="header"><Link className="brand" href="/">Business Calculator Hub</Link><nav className="nav"><Link href="/">Calculators</Link><Link href="/guides">Guides</Link><Link href="/ai-tools">AI Tools</Link></nav></header><section className="hero heroCompact"><p className="eyebrow">BUSINESS KNOWLEDGE HUB</p><h1>Guides that turn numbers into better decisions.</h1><p className="lead">Practical explanations connected directly to calculators and software guides—learn, test and act in one place.</p></section><section className="guideGrid">{guides.map(g=><Link className="guideCard" href={g.href} key={g.href}><span className="tag">{g.tag}</span><h2>{g.title}</h2><p>{g.text}</p><strong>Read guide →</strong></Link>)}</section><section className="ctaPanel"><div><p className="eyebrow">FREE INTERACTIVE TOOLS</p><h2>Turn the formulas into your own numbers.</h2><p>Calculate compensation, freelance rates, commission, ROI, markup, profit margin and break-even points.</p></div><Link className="primary" href="/#calculators">Explore calculators →</Link></section><footer className="footer"><span>© 2026 Business Calculator Hub</span><div><Link href="/affiliate-disclosure">Affiliate Disclosure</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></footer></main>}