import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata:Metadata={title:'Business Guides, Freelance Tips & Financial Formulas',description:'Practical business guides covering profit margin, break-even, freelance pricing, salary conversion, markup and AI tools.',alternates:{canonical:'/guides'}};

const guides=[
{href:'/guides/how-much-should-i-charge-as-a-freelancer',tag:'Freelancing',icon:'💼',title:'How Much Should I Charge as a Freelancer?',text:'Set a sustainable baseline using income goals, expenses and billable hours.'},
{href:'/guides/what-is-a-good-profit-margin',tag:'Profitability',icon:'📈',title:'What Is a Good Profit Margin?',text:'Learn why healthy margins vary and how to evaluate your own trend.'},
{href:'/guides/how-to-calculate-markup-from-cost',tag:'Pricing',icon:'🏷️',title:'How to Calculate Markup From Cost',text:'Turn cost and markup into selling price and understand markup versus margin.'},
{href:'/guides/how-to-calculate-profit-margin',tag:'Profitability',icon:'%',title:'How to Calculate Profit Margin',text:'Formula, examples and a direct path to the free margin calculator.'},
{href:'/guides/how-to-calculate-break-even-point',tag:'Planning',icon:'◎',title:'How to Calculate Break-Even Point',text:'Understand contribution margin and estimate the sales volume needed to cover costs.'},
{href:'/guides/freelance-hourly-rate',tag:'Freelancing',icon:'⌁',title:'How to Calculate Your Freelance Hourly Rate',text:'Build a sustainable rate around income goals, expenses and realistic billable hours.'},
{href:'/guides/salary-to-hourly-rate',tag:'Compensation',icon:'↔',title:'Salary to Hourly Rate',text:'Convert annual salary into an hourly equivalent and compare compensation more clearly.'},
{href:'/guides/25-an-hour-is-how-much-a-year',tag:'Pay Breakdown',icon:'$25',title:'$25 an Hour Is How Much a Year?',text:'Annual, monthly, weekly and daily breakdown with an interactive conversion tool.'},
{href:'/guides/30-an-hour-is-how-much-a-year',tag:'Pay Breakdown',icon:'$30',title:'$30 an Hour Is How Much a Year?',text:'See the annual equivalent and calculate a different schedule in seconds.'},
{href:'/ai-tools/best-ai-tools-for-small-business',tag:'AI & Software',icon:'AI',title:'Best AI Tools for Small Business',text:'A growing buyer guide for automation, productivity and business operations.'},
{href:'/ai-tools/creao',tag:'AI Review',icon:'✦',title:'CREAO AI Review',text:'A practical look at CREAO for businesses exploring AI-powered workflows.'}];

export default function GuidesPage(){return <main className="shell">
<header className="header"><Link className="brand" href="/">Business Calculator Hub</Link><nav className="nav"><Link href="/#calculators">Calculators</Link><Link href="/guides">Guides</Link><Link href="/ai-tools">AI Tools</Link><Link className="advertiseNav" href="/advertise">📣 Advertise with us</Link></nav></header>
<section className="hero heroCompact"><p className="eyebrow">BUSINESS KNOWLEDGE HUB</p><h1>Learn the formula. Understand the decision. Use the tool.</h1><p className="lead">Clear business guides for pricing, profitability, compensation and planning—with direct links to calculators so you can immediately test your own numbers.</p><div className="heroActions"><Link className="primary" href="#all-guides">Browse guides →</Link><Link className="secondary" href="/#calculators">Open calculators</Link></div><div className="trustRow"><span>✓ Practical examples</span><span>✓ Free calculators</span><span>✓ No signup</span><span>✓ Built for small business</span></div></section>
<section className="valueStrip"><div><strong>11</strong><span>Practical guides</span></div><div><strong>6+</strong><span>Interactive calculators</span></div><div><strong>4</strong><span>Core business topics</span></div><div><strong>0</strong><span>Account required</span></div></section>
<section id="all-guides" className="sectionBlock"><div className="sectionHeading"><div><p className="eyebrow">EXPLORE BY QUESTION</p><h2>Choose what you need to solve.</h2></div><p>Start with the business question that matters now. Every guide is written to get you from explanation to action quickly.</p></div><div className="guideGrid">{guides.map(g=><Link className="guideCard" href={g.href} key={g.href}><span className="toolIcon">{g.icon}</span><span className="tag" style={{display:'block',marginTop:18}}>{g.tag}</span><h2>{g.title}</h2><p>{g.text}</p><strong>Read guide →</strong></Link>)}</div></section>
<section className="splitFeature"><div className="featureCopy"><p className="eyebrow">LEARN + CALCULATE</p><h2>Do not stop at the formula.</h2><p>Once you understand the concept, use the matching calculator to test different scenarios and make the result useful for a real decision.</p><Link className="secondary dark" href="/#calculators">Explore calculators →</Link></div><div className="featureList"><Link href="/profit-margin-calculator"><span>Profitability</span><strong>Profit Margin Calculator</strong><em>Calculate →</em></Link><Link href="/break-even-calculator"><span>Planning</span><strong>Break-even Calculator</strong><em>Calculate →</em></Link><Link href="/freelance-rate-calculator"><span>Freelancing</span><strong>Freelance Rate Calculator</strong><em>Calculate →</em></Link><Link href="/salary-to-hourly-calculator"><span>Compensation</span><strong>Salary to Hourly Calculator</strong><em>Calculate →</em></Link></div></section>
<section className="sponsorCallout"><div><span className="sponsorLabel">FOR BRANDS & PARTNERS</span><h2>Reach readers actively researching business decisions.</h2><p>Sponsor a relevant guide or place your product in front of freelancers, entrepreneurs and small-business users.</p></div><Link className="primary" href="/advertise">Advertise with us →</Link></section>
<footer className="footer"><span>© 2026 Business Calculator Hub</span><div><Link href="/advertise">Advertise with us</Link><Link href="/affiliate-disclosure">Affiliate Disclosure</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></footer>
</main>}