import type{Metadata}from'next';
import Link from'next/link';

export const metadata:Metadata={title:'AI Tools, CRM & Software for Small Business',description:'Practical software, CRM and AI guides for entrepreneurs, freelancers and small businesses.',alternates:{canonical:'/ai-tools'}};

const software=[
{href:'/ai-tools/wizstar',tag:'AI VIDEO & MARKETING',icon:'▶',title:'Wizstar AI Video',text:'Create marketing videos from product assets and localize existing video with AI-powered translation and lip sync.'},
{href:'/ai-tools/base44',tag:'AI APP BUILDER',icon:'44',title:'Base44',text:'Explore an AI-assisted app builder for internal tools, workflow experiments and rapid business application prototyping.'},
{href:'/ai-tools/riibase',tag:'FEATURED CRM',icon:'CRM',title:'Riibase CRM',text:'Explore Riibase as an all-in-one CRM option for customer management, sales workflows and automation.'},
{href:'/ai-tools/best-crm-for-small-business',tag:'CRM BUYER GUIDE',icon:'◎',title:'Best CRM for Small Business',text:'Compare adoption, automation, integrations and cost before choosing a CRM platform.'},
{href:'/ai-tools/creao',tag:'AI AUTOMATION',icon:'✦',title:'CREAO AI',text:'Explore potential business use cases, strengths and considerations for AI-powered workflows.'},
{href:'/ai-tools/best-ai-tools-for-small-business',tag:'AI BUYER GUIDE',icon:'AI',title:'Best AI Tools for Small Business',text:'A growing guide to AI tools across automation, productivity and business operations.'}
];

export default function AiTools(){return <main className="shell">
<header className="header"><Link className="brand" href="/">Business Calculator Hub</Link><nav className="nav"><Link href="/#calculators">Calculators</Link><Link href="/guides">Guides</Link><Link href="/ai-tools">AI Tools</Link><Link className="advertiseNav" href="/advertise">📣 Advertise with us</Link></nav></header>
<section className="hero heroCompact"><p className="eyebrow">AI, CRM & SOFTWARE GUIDES</p><h1>Choose business software with less guesswork.</h1><p className="lead">Practical research for freelancers, entrepreneurs and small businesses comparing CRM, AI, automation and productivity tools.</p><div className="heroActions"><Link className="primary" href="#software-guides">Explore software guides →</Link><Link className="secondary" href="/guides">Business guides</Link></div><div className="trustRow"><span>✓ Practical use cases</span><span>✓ Clear buyer guides</span><span>✓ Business focused</span><span>✓ Transparent affiliate disclosure</span></div></section>
<section className="valueStrip"><div><strong>CRM</strong><span>Customer management</span></div><div><strong>AI</strong><span>Automation & productivity</span></div><div><strong>B2B</strong><span>Small-business focus</span></div><div><strong>Free</strong><span>Research & guides</span></div></section>
<section id="software-guides" className="sectionBlock"><div className="sectionHeading"><div><p className="eyebrow">SOFTWARE RESEARCH</p><h2>Start with the problem you want software to solve.</h2></div><p>Explore focused reviews and buyer guides, then compare each option against your workflow, budget and business priorities.</p></div><div className="guideGrid">{software.map(item=><Link className="guideCard" href={item.href} key={item.href}><span className="toolIcon">{item.icon}</span><span className="tag" style={{display:'block',marginTop:18}}>{item.tag}</span><h2>{item.title}</h2><p>{item.text}</p><strong>Explore →</strong></Link>)}</div></section>
<section className="splitFeature"><div className="featureCopy"><p className="eyebrow">HOW TO CHOOSE</p><h2>Evaluate software by business impact, not feature count.</h2><p>Prioritize adoption, integrations, automation, total cost and the problem the tool will actually solve for your team.</p><Link className="secondary dark" href="/ai-tools/best-crm-for-small-business">Read the CRM buyer guide →</Link></div><div className="featureList"><Link href="/ai-tools/riibase"><span>CRM</span><strong>Customer & sales workflows</strong><em>Explore →</em></Link><Link href="/ai-tools/creao"><span>AI</span><strong>Automation workflows</strong><em>Explore →</em></Link><Link href="/guides"><span>Learn</span><strong>Business decision guides</strong><em>Browse →</em></Link><Link href="/#calculators"><span>Calculate</span><strong>Free business calculators</strong><em>Open →</em></Link></div></section>
<section className="sponsorCallout"><div><span className="sponsorLabel">SOFTWARE BRANDS</span><h2>Put your product in front of people actively comparing business tools.</h2><p>We accept relevant sponsorship and advertising proposals from SaaS, CRM, fintech, productivity and business-service brands.</p></div><Link className="primary" href="/advertise">Advertise with us →</Link></section>
<footer className="footer"><span>© 2026 Business Calculator Hub</span><div><Link href="/advertise">Advertise with us</Link><Link href="/affiliate-disclosure">Affiliate Disclosure</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></footer>
</main>}