import type { Metadata } from 'next';import Link from 'next/link';
export const metadata:Metadata={title:'Calculadoras para Empresas, MEI e Freelancers no Brasil',description:'Calculadoras gratuitas em português para precificação, margem, ROI, CAC/LTV, ponto de equilíbrio, freelancer e decisões de pequenos negócios.',alternates:{canonical:'/pt-br',languages:{'en':'/','pt-BR':'/pt-br'}}};
const tools=[
['/pt-br/calculadora-preco-venda','R$','Calculadora de Preço de Venda','Calcule o preço a partir do custo e da margem desejada.'],
['/pt-br/calculadora-markup','%','Calculadora de Markup','Transforme custos e margem em um multiplicador de preço.'],
['/pt-br/calculadora-margem-lucro','↗','Calculadora de Margem de Lucro','Descubra quanto da receita realmente vira margem.'],
['/pt-br/calculadora-ponto-equilibrio','◎','Ponto de Equilíbrio','Veja quanto precisa vender para cobrir os custos.'],
['/pt-br/calculadora-roi','ROI','Calculadora de ROI','Meça o retorno percentual de um investimento.'],
['/pt-br/calculadora-cac-ltv','×','Calculadora de CAC e LTV','Compare custo de aquisição e valor do cliente.'],
['/pt-br/calculadora-freelancer','R$','Quanto cobrar como freelancer','Monte uma taxa por hora sustentável para seu trabalho.'],
['/pt-br/calculadora-runway','◷','Runway do negócio','Estime por quantos meses o caixa sustenta a operação.']];
export default function Brasil(){return <main className="shell"><section className="hero heroCompact"><p className="eyebrow">BUSINESS CALCULATOR HUB · BRASIL</p><h1>Calculadoras gratuitas para decisões melhores no seu negócio.</h1><p className="lead">Ferramentas em português para empreendedores, MEIs, freelancers e pequenas empresas calcularem preços, margens, retorno, aquisição de clientes e planejamento financeiro.</p><div className="heroActions"><a className="primary" href="#calculadoras">Ver calculadoras →</a><Link className="secondary" href="/">English / Global</Link></div><div className="trustRow"><span>✓ 100% gratuitas</span><span>✓ Sem cadastro</span><span>✓ Resultados em segundos</span><span>✓ Feitas para negócios</span></div></section><section className="sectionBlock" id="calculadoras"><div className="sectionHeading"><div><p className="eyebrow">FERRAMENTAS PARA O BRASIL</p><h2>Comece pela decisão que você precisa tomar.</h2></div><p>O mercado brasileiro já tem forte procura por ferramentas para CLT, PJ, MEI, precificação e gestão. Nossa expansão começa pelas calculadoras empresariais que compartilham a mesma lógica global e depois avança para cálculos específicos da legislação brasileira.</p></div><div className="toolGrid">{tools.map(([href,icon,title,text])=><Link href={href} className="toolCard" key={href}><span className="toolIcon">{icon}</span><h3>{title}</h3><p>{text}</p><strong>Calcular →</strong></Link>)}</div></section><section className="splitFeature"><div className="featureCopy"><p className="eyebrow">PRÓXIMA FASE</p><h2>CLT, PJ, MEI e cálculos brasileiros.</h2><p>Estamos ampliando a versão Brasil com salário líquido, CLT x PJ, custo de funcionário, pró-labore, MEI, Simples Nacional, férias, 13º e outros cálculos que dependem das regras brasileiras vigentes.</p></div><div className="featureList"><div className="advertiserPoint"><span>Trabalho</span><strong>CLT × PJ</strong></div><div className="advertiserPoint"><span>MEI</span><strong>Faturamento e DAS</strong></div><div className="advertiserPoint"><span>Empresa</span><strong>Custo de funcionário</strong></div><div className="advertiserPoint"><span>Gestão</span><strong>Pró-labore e Simples</strong></div></div></section><section className="sponsorCallout"><div><span className="sponsorLabel">ANUNCIE NO HUB · BRASIL</span><h2>Sua marca diante de empreendedores em momento de decisão.</h2><p>Estamos abrindo espaços para fintechs, ERPs, contabilidades, bancos, meios de pagamento, SaaS, educação e ferramentas para pequenos negócios. A audiência brasileira será apresentada separadamente no media kit conforme crescer.</p></div><Link className="primary" href="/advertise">Conheça os espaços →</Link></section><footer className="footer"><span>© 2026 Business Calculator Hub</span><div><Link href="/">Global</Link><Link href="/advertise">Anuncie</Link><Link href="/affiliate-disclosure">Afiliados</Link></div></footer></main>}